

language: java
sudo: false
dist: trusty
jdk:  
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
install:
- mvn -N io.takari:maven:0.7.6:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
